package text

const (
	DefaultAgentIntellect = "MINIMAL"
	DefaultAgentModel     = "gemini-flash-lite-latest"
	DefaultAgentName      = "Gaia"
	DefaultAgentPersona   = "Your name is " + DefaultAgentName + ". You are a CLI tool. You respond exclusively in plaintext code snippets that can be executed (or compiled) as is. Never format your responses using markdown. If no language is specified, write code in POSIX-compliant sh (or PostgreSQL if dealing with SQL). Otherwise, write the code in the language that the user mentions. Always use the most portable shell syntax (e.g. the oldest, most widely supported). Always use the newest syntax if dealing with other languages. Prefer tab indentation to spaces. Never introduce yourself."
	DefaultCensorRating   = "BLOCK_MEDIUM_AND_ABOVE"
	DefaultDbPath         = "/tmp/gaia.sqlite3"
	DefaultEnvPath        = ".env"

	EnvPrefix         = "GAIA_"
	EnvAgentIntellect = EnvPrefix + "AGENT_INTELLECT"
	EnvAgentModel     = EnvPrefix + "AGENT_MODEL"
	EnvAgentPersona   = EnvPrefix + "AGENT_PERSONA"
	EnvApiKey         = EnvPrefix + "AGENT_KEY"
	EnvCensorRating   = EnvPrefix + "AGENT_CENSOR_RATING"
	EnvDbPath         = EnvPrefix + "DB_PATH"
	EnvDotenvPath     = EnvPrefix + "ENV_FILE"

	ErrNoApiKey = "No " + EnvApiKey + "!"
	ErrNoPrompt = "No prompt provided!"

	FlagAttachmentHelp              = "Attach a file."
	FlagAttachmentOptionLong        = "read"
	FlagEnvHelp                     = "Path to dotenv file."
	FlagEnvOptionLong               = "env"
	FlagForgetAllHelp               = "Wipe entire transcript."
	FlagForgetAllOptionLong         = "amnesia"
	FlagForgetTopicHelp             = "Forget the current topic."
	FlagForgetTopicOptionLong       = "forget"
	FlagHelpHelp                    = "Show this message."
	FlagHelpOptionLong              = "help"
	FlagHelpOptionShort             = "h"
	FlagNsfwHelp                    = "Disable safeguards regardless of ENV settings."
	FlagNsfwOptionLong              = "nsfw"
	FlagPreserveContextHelp         = "Preserve conversation context."
	FlagPreserveContextOptionLong   = "related"
	FlagPreserveContextOptionShort  = "r"
	FlagPrintEnvHelp                = "Print Gaia's current settings."
	FlagPrintEnvOptionLong          = "print-env"
	FlagPrintLastResponseHelp       = "Print the last response verbatim."
	FlagPrintLastResponseOptionLong = "echo"
	FlagPrintVersionHelp            = "Print the current release tag."
	FlagPrintVersionOptionLong      = "version"

	PrintCensored         = " \033[1;31;40m CENSORED \033[0m "
	PrintCopyrighted      = " \033[1;31;40m COPYRIGHT \033[0m "
	PrintErr              = " \033[1;31;40m ERR \033[0m "
	PrintForgetEverything = "Wipe transcript from the database?"
	PrintForgetTopic      = "Forget the current conversation?"
	PrintGaia             = "\n \033[1mGAIA - Gaia AI Agent\033[0m\n\n"
	PrintHelpUsage        = "\n \033[1mUsage\033[0m: `gaia \"What's my IP address?\" | sh`\n\n\n"
	PrintHuh              = "Huh...?"
	PrintTokensExhausted  = " \033[1;31;40m TOKENS EXHAUSTED \033[0m "
	PrintVersion          = "v0.5.5 (main)"
	PrintYesOrNo          = " [y/N] "

	SqlCreateTable        = "CREATE TABLE IF NOT EXISTS transcript (id TEXT, ts TEXT, is_agent INT, body TEXT)"
	SqlInsertRow          = "INSERT INTO transcript (id, ts, is_agent, body) VALUES (?, ?, ?, ?)"
	SqlGetConversation    = "SELECT is_agent, body FROM transcript WHERE id = ?"
	SqlGetCurrentId       = "SELECT id FROM transcript ORDER BY ts DESC LIMIT 1"
	SqlGetLastResponse    = "SELECT body FROM transcript WHERE is_agent = true ORDER BY ts DESC LIMIT 1"
	SqlTruncateTopic      = "DELETE FROM transcript WHERE id = (SELECT id FROM transcript ORDER BY ts DESC LIMIT 1); VACUUM"
	SqlTruncateTranscript = "DELETE FROM transcript ; VACUUM"
)
